### ISSUE TITLE
Please change the output color

### ISSUE THREAD

**Issue by attaattaatta** [Releem/mysqlconfigurer#109]
Hello,

Running on Ubuntu 20.04

`RELEEM_MYSQL_MEMORY_LIMIT=2000 RELEEM_API_KEY=c539ee61-******** RELEEM_CRON_ENABLE=1 bash -c "$(curl -L https://releem.s3.amazonaws.com/install.sh)"
`
Become painful - https://i.imgur.com/02bDQjj.png

Could you be so kind to change blue color to something more visible
Thx

**Comment by drupaladmin** [comment]
Hi, Thanks for the issue. We'll fix it soon.

**Comment by drupaladmin** [comment]
This issue has already been fixed in the latest version @attaattaatta
