### ISSUE TITLE
Connect to mysql via socket

### ISSUE THREAD

**Issue by drupaladmin** [Releem/mysqlconfigurer#117]
How to connect to MySQL via unix socket?

**Comment by kochetovd** [comment]
https://github.com/Releem/mysqlconfigurer/commit/965a31646c03086f424e9ae30ec99dd8d08b5d01

Added environment variables RELEEM_MYSQL_HOST and RELEEM_MYSQL_PORT to set a custom ip for connecting to mysql. The value of RELEEM_MYSQL_HOST can be ip or socket.
