### ISSUE TITLE
Releem Agent stopped after server reboot

### ISSUE THREAD

**Issue by drupaladmin** [Releem/mysqlconfigurer#122]
Releem Agent stopped after I reboot server or restart MySQL. After that there are no metrics in Releem Customer Portal

**Comment by kochetovd** [comment]
https://github.com/Releem/mysqlconfigurer/commit/cdec97f8f030d9d2011a657380509c9615d2c16d
https://github.com/Releem/mysqlconfigurer/commit/62303c060307ba2396e712e613918900b0b1076f

Changed the error handler
