### ISSUE TITLE
During installation /etc/mysql/my.cnf was broke

### ISSUE THREAD

**Issue by drupaladmin** [Releem/mysqlconfigurer#126]
I tried the automatic install, but it failed. 

The error:
mysqladmin: Can't read dir of '/etc/mysql/mariadb.conf.d/!includedir /etc/mysql/releem.conf.d' (Errcode: 2 \"No such file or directory\")

something to do with my conf file that mysql was unable to start again. I freaked out and erased what whas added by releem.

this is what I kink of remember:

at the bottom of /etc/mysql/my.cnf looks like this:
!includedir /etc/mysql/conf.d/
!includedir /etc/mysql/mariadb.conf.d/

during the releem install it changed the bottom of /etc/mysql/my.cnf to something like this:
!includedir /etc/mysql/conf.d/
!includedir /etc/mysql/mariadb.conf.d/!includedir /somepath/releem/!includedir

mysql was unable to start when that happened.

Im running the latest mariaDB and I use https://www.hestiacp.com/ control panel.

**Comment by drupaladmin** [comment]
It is the issue. The root cause of that issue is no empty line at the end of the file. We'll fix it soon.

The problem is in the last string of /etc/mysql/my.cnf

To fix the problem, you should move !includedir /etc/mysql/releem.conf.d on the new line and start installation one more time.

**Comment by kochetovd** [comment]
https://github.com/Releem/mysqlconfigurer/commit/92fc3a34cf23a238adfece62f6a254dcaeb32909

Added a line break when adding a directive **includedir**
