### ISSUE TITLE
Issue with using xtrabackup/mariadbbackup error while setting value '70.000000' to 'innodb_max_dirty_pages_pct'

### ISSUE THREAD

**Issue by drupaladmin** [Releem/mysqlconfigurer#180]
I have an issue with using xtrabackup/mariadbbackup with the latest Releem config recommendations. Specifically, the Releem engine set a float where xtrabackup was expecting an integer. See the following error:
Job execution error: Unknown suffix '.' used for variable 'innodb_max_dirty_pages_pct' (value '70.000000')
/usr/bin/xtrabackup: Error while setting value '70.000000' to 'innodb_max_dirty_pages_pct'

**Comment by kochetovd** [comment]
This problem is related to God in the software used
https://jira.percona.com/browse/PXB-1807 - fixed a problem in the version 
2.4.15, 8.0.7
https://jira.mariadb.org/browse/MDEV-20286 - The problem has not been fixed yet
