### ISSUE TITLE
Can't apply config with innodb_max_dirty_pages_pct on MySQL 5.5

### ISSUE THREAD

**Issue by drupaladmin** [Releem/mysqlconfigurer#183]
For my MySQL 5.5.62 server, where I need to apply the recommendations manually, I have some difficulties because the proposed configuration sometimes prevented to start the server. It looks like releem propose parameters that are not all compatible with 5.5. I’ve tested the configuration a lot if times and isolated these two issues in the releem config.

innodb_max_dirty_pages_pct=70.000000 ### Previous value =75  ->  remove the .00000 solves it

**Comment by kochetovd** [comment]
the problem has been fixed in the platform version 1.6.5.
The new configuration will be generated after August 11, 2023, 12:00 GMT
