### ISSUE TITLE
Recommendation innodb_buffer_pool_size to more than RAM is available

### ISSUE THREAD

**Issue by liroy3000** [Releem/mysqlconfigurer#24]
MySQLTuner recommendation to set the value of innodb_buffer_pool_size to more than RAM is available
Example:
cat .mysqlconfigurer/z_aiops_mysql.conf 
...
innodb_buffer_pool_size = 3019898880 ### Previous value : 1073741824
...

free -h
             total       used       free     shared    buffers     cached
Mem:          4.0G       3.7G       327M        87M        60M       1.3G
-/+ buffers/cache:       2.3G       1.7G

**Comment by drupaladmin** [comment]
You could use the -m option to limit memory limit for MySQL in MBs.
For example:
mysqlconfigurer.sh -k your_api_key -m 1024
