### ISSUE TITLE
memory limit is wrong in app

### ISSUE THREAD

**Issue by NextBasket-Petyo** [Releem/mysqlconfigurer#255]
Hello
I configured the MySQL memory limit of 26624 via docker environment variable 

this seems to be correct in the /opt/releem/releem.conf 
```shell
# MemoryLimit int `hcl:"memory_limit"`
# Defaults to 0, Mysql memory usage limit.
memory_limit=26624
```

but in the entry for the server in https://app.releem.com/
I see Memory Limit 9957 MB:
<img width="553" alt="image" src="https://github.com/Releem/mysqlconfigurer/assets/100193556/047b9f23-dcb5-4a23-9885-be2a134358d1">

**Comment by drupaladmin** [comment]
Thanks for reaching out. 

It takes up to 12 hours to update limit in the dashboard and up to 3 days to get first recommendations.
we have 2 feature request on that:
https://github.com/Releem/mysqlconfigurer/discussions/232
https://github.com/Releem/mysqlconfigurer/discussions/208

If you just added the server, I suggest you to delete server and add new with correct memory limit from the start.
