### ISSUE TITLE
Cancel Subscription link still shows up for canceled subscription

### ISSUE THREAD

**Issue by yoni-yad2** [Releem/mysqlconfigurer#271]
1. ![image](https://github.com/Releem/mysqlconfigurer/assets/103036539/344a0221-9c34-4348-a6f3-bc77ab96d5be)

2. ![image](https://github.com/Releem/mysqlconfigurer/assets/103036539/8972f4b6-a28d-49d9-9282-9284709b03bc)

3. ![image](https://github.com/Releem/mysqlconfigurer/assets/103036539/3405ac12-04f9-4482-a1dd-bb090ef36fd9)

Link should be hidden for cancelled subscription

**Comment by drupaladmin** [comment]
Fixed in the latest update of Releem Customer Portal
