### ISSUE TITLE
Unable to apply configuration and Latency graph is not working

### ISSUE THREAD

**Issue by drupaladmin** [Releem/mysqlconfigurer#272]
forge@CS964-MySQL:~$ sudo ls -la /etc/mysql/releem.conf.d/
total 16
drw-r--r-- 2 root root 4096 Feb 27 16:22 .
drwxr-xr-x 5 root root 4096 Feb 28 00:08 ..
-rw-r----- 1 root root  120 Feb 24 23:40 collect_metrics.cnf
-rw-r----- 1 root root  679 Mar  1 09:41 z_aiops_mysql.cnf

**Comment by drupaladmin** [comment]
There are incorrect permissions, might be the issue in the installation process.

Please run:
chmod -R 755 /etc/mysql/releem.conf.d
systemctl restart mysql

**Comment by kochetovd** [comment]
https://github.com/Releem/mysqlconfigurer/commit/bc597e05b53d8b6c41e1c0009087b76a6ccd7f4e
