### ISSUE TITLE
These variables can't be changed in RDS Aurora

### ISSUE THREAD

**Issue by drupaladmin** [Releem/mysqlconfigurer#281]
### Cannot be changed ###
innodb_log_file_size
innodb_buffer_pool_instances
innodb_buffer_pool_chunk_size

**Comment by jaiment** [comment]
Full documentation here
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Reference.ParameterGroups.html#AuroraMySQL.Reference.Parameters.Inapplicable

**Comment by drupaladmin** [comment]
Thanks for your patience. @jaiment 

It was fixed. You shouldn't get recommendations on variables that couldn't be changed for RDS Aurora
