### ISSUE TITLE
Internal server error when MySQL server contains 2500 databases

### ISSUE THREAD

**Issue by drupaladmin** [Releem/mysqlconfigurer#30]
# 500 Internal Server Error Oh no! Something bad happened. Please check supported MySQL versions. Thanks.
mysql: percona-server-server-5.6 5.6.39-83.1-1.bionic

**Comment by drupaladmin** [comment]
For MySQLTuner was set "skipsize" option.
Did you edit the script or execute as is?

**Comment by drupaladmin** [comment]
When the "skipsize" options were removed file z_aiops_mysql.cnf contains {«message»: «Internal server error»}

**Comment by drupaladmin** [comment]
Report filesize more than 6Mb it is limit for Amazon service and cause of the problem.

We could try to compress the report before send it to service.

**Comment by hkirsman** [comment]
I tried Releem on aws and got the same contents to the message in the /tmp/.mysqlconfigurer/z_aiops_mysql.cnf file:

# 500 Internal Server Error Oh no! Something bad happened. Please check supported MySQL versions. Thanks.

**Comment by drupaladmin** [comment]
Hey Hannes, thank you for the report.

Please try to run Releem Agent one more time and send me please the IP address of your server on the email hello@releem.com

**Comment by drupaladmin** [comment]
#86
