### ISSUE TITLE
Autosize of innodb_buffer_pool_chunk_size in MariaDB

### ISSUE THREAD

**Issue by drupaladmin** [Releem/mysqlconfigurer#302]
innodb_buffer_pool_chunk_size in MariaDB will get autosized based on innodb_buffer_pool_size. 

should we use it for MariabDb?

**Comment by kochetovd** [comment]
If innodb_buffer_pool_chunk_size setting autosize (0), resulting in innodb_buffer_pool_size/64.
Redeem the initial value recommends a similar value, but may later change the value depending on the workflow.
