### ISSUE TITLE
Incorrect max value for innodb_log_file_size in docs

### ISSUE THREAD

**Issue by hkirsman** [Releem/mysqlconfigurer#315]
https://releem.com/docs/mysql-performance-tuning/innodb_log_file_size

Maximum Value is not 512MB, but 512GB, or rather "The combined size of log files (innodb_log_file_size * innodb_log_files_in_group) cannot exceed a maximum value that is slightly less than 512GB.". 512MB is certainly far from it, I've tried 1GB myself.

https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_log_file_size

**Comment by drupaladmin** [comment]
@hkirsman Thanks for the issue. We'll fix it ASAP

**Comment by drupaladmin** [comment]
Fixed
