### ISSUE TITLE
MySQL Root User password is stored in web cache

### ISSUE THREAD

**Issue by Ragowit** [Releem/mysqlconfigurer#321]
I noticed the Releem Agent was not running for some reason, and followed the Automatic Installation tool to reinstall it again. When focus was on the "MySQL Root User password" input box so did I notice that it had a suggestion for my password from when I used it previously.

I believe this can be a security issue.

I think by adding autocomplete="off" on the input-field will solve the issue.

**Comment by drupaladmin** [comment]
Thank you, great suggestion. We'll try to fix it.

Re unavailable Releem Agent please send me to hello@releem.com Releem Agent logs to find the root cause:
journalctl -u releem-agent

**Comment by drupaladmin** [comment]
@Ragowit Fixed that in the latest release
