### ISSUE TITLE
Can't load Query Analytics

### ISSUE THREAD

**Issue by drupaladmin** [Releem/mysqlconfigurer#336]
I was never able to get any query analytics loaded, it always just had the Load Data link, and clicking it showed a loader with "this process may take a few minutes" but it never loaded anything.

**Comment by kochetovd** [comment]
There was an error when collecting data from the table

 `Scan error on column index 10, name "SUM_ROWS_SENT": converting driver.Value type []uint8 ("18446744073709551614") to a int: value out of range `

The error has been corrected in commit https://github.com/Releem/mysqlconfigurer/commit/06265a8037e8f36a8d08721cd56c6c254deaeca2
