### ISSUE TITLE
Query Analytics is showing a database name that does not exist on my db server

### ISSUE THREAD

**Issue by drupaladmin** [Releem/mysqlconfigurer#357]
I am seeing the following listed as a slow query but it is showing a database name that does not exist on my db server. Where could this be coming from?

Attachment 1 is the query from Releem. Notice the database name is Opcotest. Attachment 2 is the show databases command from the database server. Notice there is no database name listed as Opcotest.

**Comment by stevefxp1** [comment]
Any update on when this will be fixed?

**Comment by drupaladmin** [comment]
We've fixed this issue and plan to deploy the fix this week.

**Comment by stevefxp1** [comment]
Ok thanks...please let me know when the fix goes out, so i can reset and seeing the artifact query is gone.Sent from my T-Mobile 5G Device
-------- Original message --------From: Roman Agabekov ***@***.***> Date: 10/7/24  15:23  (GMT-05:00) To: Releem/mysqlconfigurer ***@***.***> Cc: stevefxp1 ***@***.***>, Mention ***@***.***> Subject: Re: [Releem/mysqlconfigurer] Query Analytics is showing a database name that does not exist on my db server (Issue #357) 
@stevefxp1 We've fixed this issue and plan to deploy the fix this week.

**Comment by stevefxp1** [comment]
I received an agent update this morning...is this the fix?
