### ISSUE TITLE
Edit database name

### ISSUE THREAD

**Issue by moisesrodriguez** [Releem/mysqlconfigurer#360]
For example this database was created by a third-party service and the name is not intuitive to know what database this is. Being able to edit the name, would be a simple but yet very helpful feature.

![CleanShot 2024-10-08 at 12 27 16](https://github.com/user-attachments/assets/94ea37bd-e559-4085-b3a8-35911929250f)

**Comment by drupaladmin** [comment]
@moisesrodriguez Thanks for the issue.

We have a feature request on that https://github.com/Releem/mysqlconfigurer/discussions/173
Please upvote it.
