### ISSUE TITLE
Docker Conteiner Memory-Limit 

### ISSUE THREAD

**Issue by politsin** [Releem/mysqlconfigurer#42]
Some times mysql runs in docker container with memory-limits (`-m` flag)
and has no access for all server RAM
https://docs.docker.com/config/containers/resource_constraints/

There are two ways for work around
1) Ask for current limit and get recommendations that will meet the limits
2) Make recommendations for increasing container memory-limits

**Comment by drupaladmin** [comment]
In last release we added option -m to set memory limit for MySQL in MBs
