### ISSUE TITLE
[!!] Attempted to use login credentials from Debian maintenance account, but they failed.

### ISSUE THREAD

**Issue by vistar** [Releem/mysqlconfigurer#51]
~/.my.cnf is created, but not used.

Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux
mariadb 5.5.5-10.3.23-MariaDB-0+deb10u1

https://github.com/major/MySQLTuner-perl/issues/463#issuecomment-566515917 is worked.

**Comment by drupaladmin** [comment]
Thank you for the pull request. I have merged it to dev. After testing we move it to master.

**Comment by drupaladmin** [comment]
Merged to master
