### ISSUE TITLE
Learning Mysql 

### ISSUE THREAD

**Issue by DLleno** [Releem/mysqlconfigurer#84]
I've been trying to run the script 
RELEEM_API_KEY=[YOUR_RELEEM_API_KEY] bash -c "$(curl -L https://releem.s3.amazonaws.com/install.sh)"
and it keeps saying error opening terminal: unknown
I already have .my.cnf on my root 
I hope you can help

**Comment by drupaladmin** [comment]
Hi,

Please copy output from the terminal os screenshot with the problem.
