### ISSUE TITLE
First run after install generates error in /tmp/.mysqlconfigurer/z_aiops_mysql.cnf file

### ISSUE THREAD

**Issue by arpoodle** [Releem/mysqlconfigurer#89]
Executed 
` RELEEM_API_KEY=[my key] bash -c "$(curl -L https://releem.s3.amazonaws.com/install.sh)"
`
On completion, /tmp/.mysqlconfigurer/z_aiops_mysql.cnf file contains only:

`# 500 Internal Server Error Oh no! Something bad happened. Error is:Expecting value: line 1 column 2 (char 1)`

**Comment by drupaladmin** [comment]
Hey, have you signed up at releem.com to get API key?

**Comment by arpoodle** [comment]
I'm not using a .my.cnf. I'm using the encrypted passwword from mysql_config_editor to allow access to the DB as we cannot allow unencypted passwords in plaintext

The server does not have a public IP address

**Comment by drupaladmin** [comment]
We didn't test Releem Agent with mysql_config_editor. We're going to test it.

I'll keep you informed.

**Comment by drupaladmin** [comment]
Please try to run `mysqladmin ping`.
If it runs successfully, then Releem Agent should run successfully.

**Comment by drupaladmin** [comment]
@arpoodle May I ask you did you try to run mysqladmin ping?
